### ISSUE TITLE
Improvement | Text visibility 

### ISSUE THREAD

**Issue by hsn-ali** [mirajhad/reactwebdev#2]
- Welcome to Gani Tobacco
- Choose Life, Not Tobacco: Ignite Hope, Not Cancer.

To enhance readability and ensure your message is effectively communicated, it's essential to select an appropriate color scheme for the text on your homepage. By choosing colors that contrast well with the background, you can significantly improve readability and make your message more impactful.

![Screenshot 2024-03-05 110510](https://github.com/mirajhad/reactwebdev/assets/75776012/d0dad90e-d802-4df1-9489-02e965561798)

**Comment by hsn-ali** [comment]
I can work on it if you assign me!

**Comment by MdMirajAnsari** [comment]
> I can work on it if you assign me!

Hi Hassan, you can work, fork the repo and do. Also create PR so I can merge your code as well.
